// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.gg.com/game_framework/commons-go/validator"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MailSystem_SendResponse_StatusCode int32

const (
	MailSystem_SendResponse_SUCCEED MailSystem_SendResponse_StatusCode = 0
	// 拒绝，策略上选择的是拒绝，玩家邮件满时，拒绝收邮件
	MailSystem_SendResponse_OVERFLOW_REFUSE MailSystem_SendResponse_StatusCode = 1
)

var MailSystem_SendResponse_StatusCode_name = map[int32]string{
	0: "SUCCEED",
	1: "OVERFLOW_REFUSE",
}

var MailSystem_SendResponse_StatusCode_value = map[string]int32{
	"SUCCEED":         0,
	"OVERFLOW_REFUSE": 1,
}

func (x MailSystem_SendResponse_StatusCode) String() string {
	return proto.EnumName(MailSystem_SendResponse_StatusCode_name, int32(x))
}

func (MailSystem_SendResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 9, 0}
}

type MailSystem_ReadRequest_Operator int32

const (
	MailSystem_ReadRequest_IN  MailSystem_ReadRequest_Operator = 0
	MailSystem_ReadRequest_EQ  MailSystem_ReadRequest_Operator = 1
	MailSystem_ReadRequest_GT  MailSystem_ReadRequest_Operator = 2
	MailSystem_ReadRequest_GTE MailSystem_ReadRequest_Operator = 3
	MailSystem_ReadRequest_LT  MailSystem_ReadRequest_Operator = 4
	MailSystem_ReadRequest_LTE MailSystem_ReadRequest_Operator = 5
)

var MailSystem_ReadRequest_Operator_name = map[int32]string{
	0: "IN",
	1: "EQ",
	2: "GT",
	3: "GTE",
	4: "LT",
	5: "LTE",
}

var MailSystem_ReadRequest_Operator_value = map[string]int32{
	"IN":  0,
	"EQ":  1,
	"GT":  2,
	"GTE": 3,
	"LT":  4,
	"LTE": 5,
}

func (x MailSystem_ReadRequest_Operator) String() string {
	return proto.EnumName(MailSystem_ReadRequest_Operator_name, int32(x))
}

func (MailSystem_ReadRequest_Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 12, 0}
}

type MailSystem_AttachResponse_StatusCode int32

const (
	MailSystem_AttachResponse_SUCCEED          MailSystem_AttachResponse_StatusCode = 0
	MailSystem_AttachResponse_MAIL_NOT_EXIST   MailSystem_AttachResponse_StatusCode = 1
	MailSystem_AttachResponse_ATTACH_NOT_EXIST MailSystem_AttachResponse_StatusCode = 2
	MailSystem_AttachResponse_MAIL_EXPIRE      MailSystem_AttachResponse_StatusCode = 3
)

var MailSystem_AttachResponse_StatusCode_name = map[int32]string{
	0: "SUCCEED",
	1: "MAIL_NOT_EXIST",
	2: "ATTACH_NOT_EXIST",
	3: "MAIL_EXPIRE",
}

var MailSystem_AttachResponse_StatusCode_value = map[string]int32{
	"SUCCEED":          0,
	"MAIL_NOT_EXIST":   1,
	"ATTACH_NOT_EXIST": 2,
	"MAIL_EXPIRE":      3,
}

func (x MailSystem_AttachResponse_StatusCode) String() string {
	return proto.EnumName(MailSystem_AttachResponse_StatusCode_name, int32(x))
}

func (MailSystem_AttachResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 15, 0}
}

type MailSystem_SubmitResponse_StatusCode int32

const (
	MailSystem_SubmitResponse_SUCCEED MailSystem_SubmitResponse_StatusCode = 0
	// 脚本测试失败
	MailSystem_SubmitResponse_SCRIPT_TEST_FIAL MailSystem_SubmitResponse_StatusCode = 1
)

var MailSystem_SubmitResponse_StatusCode_name = map[int32]string{
	0: "SUCCEED",
	1: "SCRIPT_TEST_FIAL",
}

var MailSystem_SubmitResponse_StatusCode_value = map[string]int32{
	"SUCCEED":          0,
	"SCRIPT_TEST_FIAL": 1,
}

func (x MailSystem_SubmitResponse_StatusCode) String() string {
	return proto.EnumName(MailSystem_SubmitResponse_StatusCode_name, int32(x))
}

func (MailSystem_SubmitResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 18, 0}
}

type MailSystem_RemoveRequest_Policy int32

const (
	MailSystem_RemoveRequest_NO          MailSystem_RemoveRequest_Policy = 0
	MailSystem_RemoveRequest_ATTACH      MailSystem_RemoveRequest_Policy = 1
	MailSystem_RemoveRequest_READ        MailSystem_RemoveRequest_Policy = 2
	MailSystem_RemoveRequest_READ_ATTACH MailSystem_RemoveRequest_Policy = 3
)

var MailSystem_RemoveRequest_Policy_name = map[int32]string{
	0: "NO",
	1: "ATTACH",
	2: "READ",
	3: "READ_ATTACH",
}

var MailSystem_RemoveRequest_Policy_value = map[string]int32{
	"NO":          0,
	"ATTACH":      1,
	"READ":        2,
	"READ_ATTACH": 3,
}

func (x MailSystem_RemoveRequest_Policy) String() string {
	return proto.EnumName(MailSystem_RemoveRequest_Policy_name, int32(x))
}

func (MailSystem_RemoveRequest_Policy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 21, 0}
}

type MailSystem_RemoveResponse_FailCause int32

const (
	MailSystem_RemoveResponse_EXIST_ATTACH   MailSystem_RemoveResponse_FailCause = 0
	MailSystem_RemoveResponse_UNREAD         MailSystem_RemoveResponse_FailCause = 1
	MailSystem_RemoveResponse_MAIL_NOT_EXIST MailSystem_RemoveResponse_FailCause = 2
)

var MailSystem_RemoveResponse_FailCause_name = map[int32]string{
	0: "EXIST_ATTACH",
	1: "UNREAD",
	2: "MAIL_NOT_EXIST",
}

var MailSystem_RemoveResponse_FailCause_value = map[string]int32{
	"EXIST_ATTACH":   0,
	"UNREAD":         1,
	"MAIL_NOT_EXIST": 2,
}

func (x MailSystem_RemoveResponse_FailCause) String() string {
	return proto.EnumName(MailSystem_RemoveResponse_FailCause_name, int32(x))
}

func (MailSystem_RemoveResponse_FailCause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 22, 0}
}

type MailSystem_RemoveGlobalEnvResponse_StatusCode int32

const (
	MailSystem_RemoveGlobalEnvResponse_SUCCEED MailSystem_RemoveGlobalEnvResponse_StatusCode = 0
	//加载全部环境失败但删除成功了,如果状态为此值，则下面env里就没有值
	MailSystem_RemoveGlobalEnvResponse_LOAD_FAIL_WITH_DEL_SUCC MailSystem_RemoveGlobalEnvResponse_StatusCode = 1
)

var MailSystem_RemoveGlobalEnvResponse_StatusCode_name = map[int32]string{
	0: "SUCCEED",
	1: "LOAD_FAIL_WITH_DEL_SUCC",
}

var MailSystem_RemoveGlobalEnvResponse_StatusCode_value = map[string]int32{
	"SUCCEED":                 0,
	"LOAD_FAIL_WITH_DEL_SUCC": 1,
}

func (x MailSystem_RemoveGlobalEnvResponse_StatusCode) String() string {
	return proto.EnumName(MailSystem_RemoveGlobalEnvResponse_StatusCode_name, int32(x))
}

func (MailSystem_RemoveGlobalEnvResponse_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 26, 0}
}

type MailSystem struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem) Reset()         { *m = MailSystem{} }
func (m *MailSystem) String() string { return proto.CompactTextString(m) }
func (*MailSystem) ProtoMessage()    {}
func (*MailSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *MailSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem.Unmarshal(m, b)
}
func (m *MailSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem.Marshal(b, m, deterministic)
}
func (m *MailSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem.Merge(m, src)
}
func (m *MailSystem) XXX_Size() int {
	return xxx_messageInfo_MailSystem.Size(m)
}
func (m *MailSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem proto.InternalMessageInfo

// 环境值，允许提供 string or float64, 不能提供int值，必须转成float64
// 表达式的字面值中只有数字类型与字符串类型，所有数字类型都为float64
type MailSystem_EnvValue struct {
	// Types that are valid to be assigned to Val:
	//	*MailSystem_EnvValue_S
	//	*MailSystem_EnvValue_F
	Val                  isMailSystem_EnvValue_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-" bson:"-"`
	XXX_unrecognized     []byte                    `json:"-" bson:"-"`
	XXX_sizecache        int32                     `json:"-" bson:"-"`
}

func (m *MailSystem_EnvValue) Reset()         { *m = MailSystem_EnvValue{} }
func (m *MailSystem_EnvValue) String() string { return proto.CompactTextString(m) }
func (*MailSystem_EnvValue) ProtoMessage()    {}
func (*MailSystem_EnvValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 0}
}

func (m *MailSystem_EnvValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_EnvValue.Unmarshal(m, b)
}
func (m *MailSystem_EnvValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_EnvValue.Marshal(b, m, deterministic)
}
func (m *MailSystem_EnvValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_EnvValue.Merge(m, src)
}
func (m *MailSystem_EnvValue) XXX_Size() int {
	return xxx_messageInfo_MailSystem_EnvValue.Size(m)
}
func (m *MailSystem_EnvValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_EnvValue.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_EnvValue proto.InternalMessageInfo

type isMailSystem_EnvValue_Val interface {
	isMailSystem_EnvValue_Val()
}

type MailSystem_EnvValue_S struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3,oneof"`
}

type MailSystem_EnvValue_F struct {
	F float64 `protobuf:"fixed64,2,opt,name=f,proto3,oneof"`
}

func (*MailSystem_EnvValue_S) isMailSystem_EnvValue_Val() {}

func (*MailSystem_EnvValue_F) isMailSystem_EnvValue_Val() {}

func (m *MailSystem_EnvValue) GetVal() isMailSystem_EnvValue_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *MailSystem_EnvValue) GetS() string {
	if x, ok := m.GetVal().(*MailSystem_EnvValue_S); ok {
		return x.S
	}
	return ""
}

func (m *MailSystem_EnvValue) GetF() float64 {
	if x, ok := m.GetVal().(*MailSystem_EnvValue_F); ok {
		return x.F
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MailSystem_EnvValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MailSystem_EnvValue_S)(nil),
		(*MailSystem_EnvValue_F)(nil),
	}
}

// 环境的包装，加入持续时间
type MailSystem_EnvWrap struct {
	Val                  *MailSystem_EnvValue `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Duration             int64                `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *MailSystem_EnvWrap) Reset()         { *m = MailSystem_EnvWrap{} }
func (m *MailSystem_EnvWrap) String() string { return proto.CompactTextString(m) }
func (*MailSystem_EnvWrap) ProtoMessage()    {}
func (*MailSystem_EnvWrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 1}
}

func (m *MailSystem_EnvWrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_EnvWrap.Unmarshal(m, b)
}
func (m *MailSystem_EnvWrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_EnvWrap.Marshal(b, m, deterministic)
}
func (m *MailSystem_EnvWrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_EnvWrap.Merge(m, src)
}
func (m *MailSystem_EnvWrap) XXX_Size() int {
	return xxx_messageInfo_MailSystem_EnvWrap.Size(m)
}
func (m *MailSystem_EnvWrap) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_EnvWrap.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_EnvWrap proto.InternalMessageInfo

func (m *MailSystem_EnvWrap) GetVal() *MailSystem_EnvValue {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *MailSystem_EnvWrap) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// 玩家信息
type MailSystem_PlayerInfo struct {
	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//其他数据,不作定义，一切符合protobuf格式的都可以，由游戏自行定义
	//        yq.protobuf.Any data = 3;
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_PlayerInfo) Reset()         { *m = MailSystem_PlayerInfo{} }
func (m *MailSystem_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MailSystem_PlayerInfo) ProtoMessage()    {}
func (*MailSystem_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 2}
}

func (m *MailSystem_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_PlayerInfo.Unmarshal(m, b)
}
func (m *MailSystem_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *MailSystem_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_PlayerInfo.Merge(m, src)
}
func (m *MailSystem_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MailSystem_PlayerInfo.Size(m)
}
func (m *MailSystem_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_PlayerInfo proto.InternalMessageInfo

func (m *MailSystem_PlayerInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MailSystem_PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MailSystem_PlayerInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 系统信息
type MailSystem_SystemInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//其他数据,不作定义，一切符合protobuf格式的都可以，由游戏自行定义
	//        yq.protobuf.Any data = 2;
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_SystemInfo) Reset()         { *m = MailSystem_SystemInfo{} }
func (m *MailSystem_SystemInfo) String() string { return proto.CompactTextString(m) }
func (*MailSystem_SystemInfo) ProtoMessage()    {}
func (*MailSystem_SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 3}
}

func (m *MailSystem_SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_SystemInfo.Unmarshal(m, b)
}
func (m *MailSystem_SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_SystemInfo.Marshal(b, m, deterministic)
}
func (m *MailSystem_SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_SystemInfo.Merge(m, src)
}
func (m *MailSystem_SystemInfo) XXX_Size() int {
	return xxx_messageInfo_MailSystem_SystemInfo.Size(m)
}
func (m *MailSystem_SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_SystemInfo proto.InternalMessageInfo

func (m *MailSystem_SystemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MailSystem_SystemInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 邮箱
type MailSystem_Box struct {
	// @inject_tag: bson:"_id"
	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty" bson:"_id"`
	GOffset  int64 `protobuf:"varint,2,opt,name=gOffset,proto3" json:"gOffset,omitempty"`
	NextId   int64 `protobuf:"varint,3,opt,name=nextId,proto3" json:"nextId,omitempty"`
	// 版本号，如果启用本地cache，用于与数据库中的版本核对的
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// @inject_tag: bson:"mails,omitempty"
	Mails map[int64]*MailSystem_Mail `protobuf:"bytes,5,rep,name=mails,proto3" json:"mails,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"mails,omitempty"`
	// @inject_tag: bson:"gmails,omitempty"
	GMails               map[int64]*MailSystem_GlobalMail `protobuf:"bytes,6,rep,name=gMails,proto3" json:"gMails,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"gmails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-" bson:"-"`
	XXX_unrecognized     []byte                           `json:"-" bson:"-"`
	XXX_sizecache        int32                            `json:"-" bson:"-"`
}

func (m *MailSystem_Box) Reset()         { *m = MailSystem_Box{} }
func (m *MailSystem_Box) String() string { return proto.CompactTextString(m) }
func (*MailSystem_Box) ProtoMessage()    {}
func (*MailSystem_Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 4}
}

func (m *MailSystem_Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_Box.Unmarshal(m, b)
}
func (m *MailSystem_Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_Box.Marshal(b, m, deterministic)
}
func (m *MailSystem_Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_Box.Merge(m, src)
}
func (m *MailSystem_Box) XXX_Size() int {
	return xxx_messageInfo_MailSystem_Box.Size(m)
}
func (m *MailSystem_Box) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_Box.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_Box proto.InternalMessageInfo

func (m *MailSystem_Box) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MailSystem_Box) GetGOffset() int64 {
	if m != nil {
		return m.GOffset
	}
	return 0
}

func (m *MailSystem_Box) GetNextId() int64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

func (m *MailSystem_Box) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MailSystem_Box) GetMails() map[int64]*MailSystem_Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

func (m *MailSystem_Box) GetGMails() map[int64]*MailSystem_GlobalMail {
	if m != nil {
		return m.GMails
	}
	return nil
}

// 邮件
type MailSystem_Mail struct {
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiverId int64                  `protobuf:"varint,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Sender     *MailSystem_PlayerInfo `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Title      string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content    string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	//是否读取 false: 未读取, true: 已读取
	Read bool `protobuf:"varint,6,opt,name=read,proto3" json:"read,omitempty"`
	// 所有附件领取完成
	AllAttachDone bool `protobuf:"varint,7,opt,name=allAttachDone,proto3" json:"allAttachDone,omitempty"`
	// 发送时间
	SendTime int64 `protobuf:"varint,8,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	// 到期时间，秒, 指终点时间，不是指间隔时间
	ExpireTime int64 `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	// 附件数组
	AttachArray []*MailSystem_Attachment `protobuf:"bytes,10,rep,name=attachArray,proto3" json:"attachArray,omitempty"`
	// 邮件扩展数据，由游戏进行解构，可以是一个4个字节的整型id,也可以是另外一个protobuf消息
	// 也可以是一个json结构的字符串，随游戏决定
	ExtendData           []byte   `protobuf:"bytes,11,opt,name=extendData,proto3" json:"extendData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_Mail) Reset()         { *m = MailSystem_Mail{} }
func (m *MailSystem_Mail) String() string { return proto.CompactTextString(m) }
func (*MailSystem_Mail) ProtoMessage()    {}
func (*MailSystem_Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 5}
}

func (m *MailSystem_Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_Mail.Unmarshal(m, b)
}
func (m *MailSystem_Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_Mail.Marshal(b, m, deterministic)
}
func (m *MailSystem_Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_Mail.Merge(m, src)
}
func (m *MailSystem_Mail) XXX_Size() int {
	return xxx_messageInfo_MailSystem_Mail.Size(m)
}
func (m *MailSystem_Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_Mail proto.InternalMessageInfo

func (m *MailSystem_Mail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MailSystem_Mail) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *MailSystem_Mail) GetSender() *MailSystem_PlayerInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MailSystem_Mail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailSystem_Mail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MailSystem_Mail) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *MailSystem_Mail) GetAllAttachDone() bool {
	if m != nil {
		return m.AllAttachDone
	}
	return false
}

func (m *MailSystem_Mail) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *MailSystem_Mail) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *MailSystem_Mail) GetAttachArray() []*MailSystem_Attachment {
	if m != nil {
		return m.AttachArray
	}
	return nil
}

func (m *MailSystem_Mail) GetExtendData() []byte {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

// 全局邮件
type MailSystem_GlobalMail struct {
	// @inject_tag: bson:"_id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	// 脚本类型,默认为gval
	ScriptType string `protobuf:"bytes,2,opt,name=scriptType,proto3" json:"scriptType,omitempty"`
	// 条件脚本 用于玩家筛选邮件的条件，无:表示全服发放
	CondScript string `protobuf:"bytes,3,opt,name=condScript,proto3" json:"condScript,omitempty"`
	// 发送者
	Sender *MailSystem_SystemInfo `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	// (可携带变量，如"${user}庆祝国庆")
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// (可携带变量，如"${user}庆祝国庆")
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 发送时间
	SendTime int64 `protobuf:"varint,7,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	// 到期时间，秒, 指终点时间，不是指间隔时间
	ExpireTime int64 `protobuf:"varint,8,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	// 附件数组
	AttachArray []*MailSystem_Attachment `protobuf:"bytes,9,rep,name=attachArray,proto3" json:"attachArray,omitempty"`
	// 邮件扩展数据，由游戏进行解构，可以是一个4个字节的整型id,也可以是另外一个protobuf消息
	// 也可以是一个json结构的字符串，随游戏决定
	ExtendData           []byte   `protobuf:"bytes,10,opt,name=extendData,proto3" json:"extendData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_GlobalMail) Reset()         { *m = MailSystem_GlobalMail{} }
func (m *MailSystem_GlobalMail) String() string { return proto.CompactTextString(m) }
func (*MailSystem_GlobalMail) ProtoMessage()    {}
func (*MailSystem_GlobalMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 6}
}

func (m *MailSystem_GlobalMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_GlobalMail.Unmarshal(m, b)
}
func (m *MailSystem_GlobalMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_GlobalMail.Marshal(b, m, deterministic)
}
func (m *MailSystem_GlobalMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_GlobalMail.Merge(m, src)
}
func (m *MailSystem_GlobalMail) XXX_Size() int {
	return xxx_messageInfo_MailSystem_GlobalMail.Size(m)
}
func (m *MailSystem_GlobalMail) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_GlobalMail.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_GlobalMail proto.InternalMessageInfo

func (m *MailSystem_GlobalMail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MailSystem_GlobalMail) GetScriptType() string {
	if m != nil {
		return m.ScriptType
	}
	return ""
}

func (m *MailSystem_GlobalMail) GetCondScript() string {
	if m != nil {
		return m.CondScript
	}
	return ""
}

func (m *MailSystem_GlobalMail) GetSender() *MailSystem_SystemInfo {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MailSystem_GlobalMail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailSystem_GlobalMail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MailSystem_GlobalMail) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *MailSystem_GlobalMail) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *MailSystem_GlobalMail) GetAttachArray() []*MailSystem_Attachment {
	if m != nil {
		return m.AttachArray
	}
	return nil
}

func (m *MailSystem_GlobalMail) GetExtendData() []byte {
	if m != nil {
		return m.ExtendData
	}
	return nil
}

// 附件
type MailSystem_Attachment struct {
	//标记，false: 未领取, true: 已领取
	Mark bool `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	// 附件数据
	//        yq.protobuf.Any data = 2;
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_Attachment) Reset()         { *m = MailSystem_Attachment{} }
func (m *MailSystem_Attachment) String() string { return proto.CompactTextString(m) }
func (*MailSystem_Attachment) ProtoMessage()    {}
func (*MailSystem_Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 7}
}

func (m *MailSystem_Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_Attachment.Unmarshal(m, b)
}
func (m *MailSystem_Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_Attachment.Marshal(b, m, deterministic)
}
func (m *MailSystem_Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_Attachment.Merge(m, src)
}
func (m *MailSystem_Attachment) XXX_Size() int {
	return xxx_messageInfo_MailSystem_Attachment.Size(m)
}
func (m *MailSystem_Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_Attachment proto.InternalMessageInfo

func (m *MailSystem_Attachment) GetMark() bool {
	if m != nil {
		return m.Mark
	}
	return false
}

func (m *MailSystem_Attachment) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 发送邮件请求
type MailSystem_SendRequest struct {
	// 不需要带邮件id,服务器会生成
	Mail                 *MailSystem_Mail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *MailSystem_SendRequest) Reset()         { *m = MailSystem_SendRequest{} }
func (m *MailSystem_SendRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_SendRequest) ProtoMessage()    {}
func (*MailSystem_SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 8}
}

func (m *MailSystem_SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_SendRequest.Unmarshal(m, b)
}
func (m *MailSystem_SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_SendRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_SendRequest.Merge(m, src)
}
func (m *MailSystem_SendRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_SendRequest.Size(m)
}
func (m *MailSystem_SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_SendRequest proto.InternalMessageInfo

func (m *MailSystem_SendRequest) GetMail() *MailSystem_Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

// 发送邮件响应,(请求就是Mail)
type MailSystem_SendResponse struct {
	// 状态码，使用了上面 StatusCode的枚举，为避免c++奔溃
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 非SUCCEED情况下的错误信息
	ErrInfo string `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	// 只有SUCCEED情况下才有值，返回成功发送的邮件对像(带有邮件id)
	Mail *MailSystem_Mail `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	// 本次移除的邮件id
	RemoveMailIds        []int64  `protobuf:"varint,4,rep,packed,name=removeMailIds,proto3" json:"removeMailIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_SendResponse) Reset()         { *m = MailSystem_SendResponse{} }
func (m *MailSystem_SendResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_SendResponse) ProtoMessage()    {}
func (*MailSystem_SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 9}
}

func (m *MailSystem_SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_SendResponse.Unmarshal(m, b)
}
func (m *MailSystem_SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_SendResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_SendResponse.Merge(m, src)
}
func (m *MailSystem_SendResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_SendResponse.Size(m)
}
func (m *MailSystem_SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_SendResponse proto.InternalMessageInfo

func (m *MailSystem_SendResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MailSystem_SendResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *MailSystem_SendResponse) GetMail() *MailSystem_Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *MailSystem_SendResponse) GetRemoveMailIds() []int64 {
	if m != nil {
		return m.RemoveMailIds
	}
	return nil
}

// 拉取邮件请求
type MailSystem_PullRequest struct {
	// 玩家id
	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	//邮件偏移，目前收到的最大邮件id
	MailOffset int64 `protobuf:"varint,2,opt,name=mailOffset,proto3" json:"mailOffset,omitempty"`
	// 变量名 对应 变量值，值可以为空，说明要取全局环境变量(值为空，并不代表不给出key)
	Env                  map[string]*MailSystem_EnvValue `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-" bson:"-"`
	XXX_unrecognized     []byte                          `json:"-" bson:"-"`
	XXX_sizecache        int32                           `json:"-" bson:"-"`
}

func (m *MailSystem_PullRequest) Reset()         { *m = MailSystem_PullRequest{} }
func (m *MailSystem_PullRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_PullRequest) ProtoMessage()    {}
func (*MailSystem_PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 10}
}

func (m *MailSystem_PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_PullRequest.Unmarshal(m, b)
}
func (m *MailSystem_PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_PullRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_PullRequest.Merge(m, src)
}
func (m *MailSystem_PullRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_PullRequest.Size(m)
}
func (m *MailSystem_PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_PullRequest proto.InternalMessageInfo

func (m *MailSystem_PullRequest) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MailSystem_PullRequest) GetMailOffset() int64 {
	if m != nil {
		return m.MailOffset
	}
	return 0
}

func (m *MailSystem_PullRequest) GetEnv() map[string]*MailSystem_EnvValue {
	if m != nil {
		return m.Env
	}
	return nil
}

// 拉取邮件响应
type MailSystem_PullResponse struct {
	// 拉取到的邮件
	Mails []*MailSystem_Mail `protobuf:"bytes,3,rep,name=mails,proto3" json:"mails,omitempty"`
	// 本次操作移除的邮件id，比如拉取的时候，正好有邮件过期
	RemoveMailIds        []int64  `protobuf:"varint,4,rep,packed,name=removeMailIds,proto3" json:"removeMailIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_PullResponse) Reset()         { *m = MailSystem_PullResponse{} }
func (m *MailSystem_PullResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_PullResponse) ProtoMessage()    {}
func (*MailSystem_PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 11}
}

func (m *MailSystem_PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_PullResponse.Unmarshal(m, b)
}
func (m *MailSystem_PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_PullResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_PullResponse.Merge(m, src)
}
func (m *MailSystem_PullResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_PullResponse.Size(m)
}
func (m *MailSystem_PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_PullResponse proto.InternalMessageInfo

func (m *MailSystem_PullResponse) GetMails() []*MailSystem_Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

func (m *MailSystem_PullResponse) GetRemoveMailIds() []int64 {
	if m != nil {
		return m.RemoveMailIds
	}
	return nil
}

// 读取请求(这里不是读取邮件，是把邮件标记为已读取)
type MailSystem_ReadRequest struct {
	// 玩家id
	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	// 需要读取的邮件id表, 除IN外，其他的只会使用数组的第0个元素,默认操作是IN
	Ids []int64 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// 本次请求使用的操作, 使用了上面 Operator 枚举，为避免c++使用奔溃
	Op int32 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	// true: 返回本次操作命中的邮件，否则不返回
	NeedMails bool `protobuf:"varint,4,opt,name=needMails,proto3" json:"needMails,omitempty"`
	// true: 返回所有已读邮件的id,包括不在本次操作内的, false: 只返回本次操作内命中的
	AllReturn            bool     `protobuf:"varint,5,opt,name=allReturn,proto3" json:"allReturn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_ReadRequest) Reset()         { *m = MailSystem_ReadRequest{} }
func (m *MailSystem_ReadRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_ReadRequest) ProtoMessage()    {}
func (*MailSystem_ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 12}
}

func (m *MailSystem_ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_ReadRequest.Unmarshal(m, b)
}
func (m *MailSystem_ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_ReadRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_ReadRequest.Merge(m, src)
}
func (m *MailSystem_ReadRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_ReadRequest.Size(m)
}
func (m *MailSystem_ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_ReadRequest proto.InternalMessageInfo

func (m *MailSystem_ReadRequest) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MailSystem_ReadRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *MailSystem_ReadRequest) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *MailSystem_ReadRequest) GetNeedMails() bool {
	if m != nil {
		return m.NeedMails
	}
	return false
}

func (m *MailSystem_ReadRequest) GetAllReturn() bool {
	if m != nil {
		return m.AllReturn
	}
	return false
}

// 读取响应
type MailSystem_ReadResponse struct {
	// 把已经设置为读取的邮件id返回，值会根据请求中的allReturn来决定
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// 本次操作命中的邮件返回,值会根据请求中的needMails来决定
	Mails                []*MailSystem_Mail `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *MailSystem_ReadResponse) Reset()         { *m = MailSystem_ReadResponse{} }
func (m *MailSystem_ReadResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_ReadResponse) ProtoMessage()    {}
func (*MailSystem_ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 13}
}

func (m *MailSystem_ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_ReadResponse.Unmarshal(m, b)
}
func (m *MailSystem_ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_ReadResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_ReadResponse.Merge(m, src)
}
func (m *MailSystem_ReadResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_ReadResponse.Size(m)
}
func (m *MailSystem_ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_ReadResponse proto.InternalMessageInfo

func (m *MailSystem_ReadResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *MailSystem_ReadResponse) GetMails() []*MailSystem_Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

// 领取附件请求
// mailId没有值，说明领取所有未被领取的附件，否则领取指定邮件中指定索引的附件
type MailSystem_AttachRequest struct {
	// 玩家id
	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	// 邮件id
	MailId int64 `protobuf:"varint,2,opt,name=mailId,proto3" json:"mailId,omitempty"`
	// 如果不存在任何元素，或为空，则是取mailId中的所有附件
	AttachIdxArray       []int32  `protobuf:"varint,3,rep,packed,name=attachIdxArray,proto3" json:"attachIdxArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_AttachRequest) Reset()         { *m = MailSystem_AttachRequest{} }
func (m *MailSystem_AttachRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_AttachRequest) ProtoMessage()    {}
func (*MailSystem_AttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 14}
}

func (m *MailSystem_AttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_AttachRequest.Unmarshal(m, b)
}
func (m *MailSystem_AttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_AttachRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_AttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_AttachRequest.Merge(m, src)
}
func (m *MailSystem_AttachRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_AttachRequest.Size(m)
}
func (m *MailSystem_AttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_AttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_AttachRequest proto.InternalMessageInfo

func (m *MailSystem_AttachRequest) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MailSystem_AttachRequest) GetMailId() int64 {
	if m != nil {
		return m.MailId
	}
	return 0
}

func (m *MailSystem_AttachRequest) GetAttachIdxArray() []int32 {
	if m != nil {
		return m.AttachIdxArray
	}
	return nil
}

// 附件响应
// 返回领取邮件的的附件数据
type MailSystem_AttachResponse struct {
	// 状态码, 使用上面StatusCode枚举，为使c++不奔溃
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 非 SUCCEED 情况下的错误信息
	ErrInfo string `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	// key: 邮件id, values：邮件中已被领取的附件
	// 只有在 SUCCEED 的情况下才存在
	// 凡key对应的邮件id，均设置为已读了
	Packs map[int64]*MailSystem_AttachmentPack `protobuf:"bytes,3,rep,name=packs,proto3" json:"packs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 本次移除的邮件id
	RemoveMailIds        []int64  `protobuf:"varint,4,rep,packed,name=removeMailIds,proto3" json:"removeMailIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_AttachResponse) Reset()         { *m = MailSystem_AttachResponse{} }
func (m *MailSystem_AttachResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_AttachResponse) ProtoMessage()    {}
func (*MailSystem_AttachResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 15}
}

func (m *MailSystem_AttachResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_AttachResponse.Unmarshal(m, b)
}
func (m *MailSystem_AttachResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_AttachResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_AttachResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_AttachResponse.Merge(m, src)
}
func (m *MailSystem_AttachResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_AttachResponse.Size(m)
}
func (m *MailSystem_AttachResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_AttachResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_AttachResponse proto.InternalMessageInfo

func (m *MailSystem_AttachResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MailSystem_AttachResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *MailSystem_AttachResponse) GetPacks() map[int64]*MailSystem_AttachmentPack {
	if m != nil {
		return m.Packs
	}
	return nil
}

func (m *MailSystem_AttachResponse) GetRemoveMailIds() []int64 {
	if m != nil {
		return m.RemoveMailIds
	}
	return nil
}

//附件包，领取附件响应中使用
type MailSystem_AttachmentPack struct {
	AttachArray          []*MailSystem_Attachment `protobuf:"bytes,1,rep,name=attachArray,proto3" json:"attachArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" bson:"-"`
	XXX_unrecognized     []byte                   `json:"-" bson:"-"`
	XXX_sizecache        int32                    `json:"-" bson:"-"`
}

func (m *MailSystem_AttachmentPack) Reset()         { *m = MailSystem_AttachmentPack{} }
func (m *MailSystem_AttachmentPack) String() string { return proto.CompactTextString(m) }
func (*MailSystem_AttachmentPack) ProtoMessage()    {}
func (*MailSystem_AttachmentPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 16}
}

func (m *MailSystem_AttachmentPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_AttachmentPack.Unmarshal(m, b)
}
func (m *MailSystem_AttachmentPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_AttachmentPack.Marshal(b, m, deterministic)
}
func (m *MailSystem_AttachmentPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_AttachmentPack.Merge(m, src)
}
func (m *MailSystem_AttachmentPack) XXX_Size() int {
	return xxx_messageInfo_MailSystem_AttachmentPack.Size(m)
}
func (m *MailSystem_AttachmentPack) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_AttachmentPack.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_AttachmentPack proto.InternalMessageInfo

func (m *MailSystem_AttachmentPack) GetAttachArray() []*MailSystem_Attachment {
	if m != nil {
		return m.AttachArray
	}
	return nil
}

// 提交邮件请求
type MailSystem_SubmitRequest struct {
	// 全局邮件对像
	Gmail *MailSystem_GlobalMail `protobuf:"bytes,1,opt,name=gmail,proto3" json:"gmail,omitempty"`
	// 测试参数，提交gmail时，如果存在测试参数，说明要测试脚本，只有测试成功了，才能添加全局邮件
	// 变量名 对应 环境值， 值可以为空，空说明要取全局环境变量（值为空，不代表key不放置）
	TestParam            map[string]*MailSystem_EnvValue `protobuf:"bytes,2,rep,name=testParam,proto3" json:"testParam,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-" bson:"-"`
	XXX_unrecognized     []byte                          `json:"-" bson:"-"`
	XXX_sizecache        int32                           `json:"-" bson:"-"`
}

func (m *MailSystem_SubmitRequest) Reset()         { *m = MailSystem_SubmitRequest{} }
func (m *MailSystem_SubmitRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_SubmitRequest) ProtoMessage()    {}
func (*MailSystem_SubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 17}
}

func (m *MailSystem_SubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_SubmitRequest.Unmarshal(m, b)
}
func (m *MailSystem_SubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_SubmitRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_SubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_SubmitRequest.Merge(m, src)
}
func (m *MailSystem_SubmitRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_SubmitRequest.Size(m)
}
func (m *MailSystem_SubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_SubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_SubmitRequest proto.InternalMessageInfo

func (m *MailSystem_SubmitRequest) GetGmail() *MailSystem_GlobalMail {
	if m != nil {
		return m.Gmail
	}
	return nil
}

func (m *MailSystem_SubmitRequest) GetTestParam() map[string]*MailSystem_EnvValue {
	if m != nil {
		return m.TestParam
	}
	return nil
}

// 提交邮件响应（提交是指运营发放全服邮件，或游戏中发放全服邮件）
type MailSystem_SubmitResponse struct {
	// 状态码, 使用上面的 StatusCode 枚举，为使c++不奔溃
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 非 SUCCEED 情况下的错误信息
	ErrInfo string `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	// 添加后的全局邮件id
	Gmailid              int64    `protobuf:"varint,3,opt,name=gmailid,proto3" json:"gmailid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_SubmitResponse) Reset()         { *m = MailSystem_SubmitResponse{} }
func (m *MailSystem_SubmitResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_SubmitResponse) ProtoMessage()    {}
func (*MailSystem_SubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 18}
}

func (m *MailSystem_SubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_SubmitResponse.Unmarshal(m, b)
}
func (m *MailSystem_SubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_SubmitResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_SubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_SubmitResponse.Merge(m, src)
}
func (m *MailSystem_SubmitResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_SubmitResponse.Size(m)
}
func (m *MailSystem_SubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_SubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_SubmitResponse proto.InternalMessageInfo

func (m *MailSystem_SubmitResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MailSystem_SubmitResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *MailSystem_SubmitResponse) GetGmailid() int64 {
	if m != nil {
		return m.Gmailid
	}
	return 0
}

// 删除全局邮件请求
type MailSystem_DeleteGlobalMailRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_DeleteGlobalMailRequest) Reset()         { *m = MailSystem_DeleteGlobalMailRequest{} }
func (m *MailSystem_DeleteGlobalMailRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_DeleteGlobalMailRequest) ProtoMessage()    {}
func (*MailSystem_DeleteGlobalMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 19}
}

func (m *MailSystem_DeleteGlobalMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailRequest.Unmarshal(m, b)
}
func (m *MailSystem_DeleteGlobalMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_DeleteGlobalMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_DeleteGlobalMailRequest.Merge(m, src)
}
func (m *MailSystem_DeleteGlobalMailRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailRequest.Size(m)
}
func (m *MailSystem_DeleteGlobalMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_DeleteGlobalMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_DeleteGlobalMailRequest proto.InternalMessageInfo

func (m *MailSystem_DeleteGlobalMailRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// 删除全局邮件响应
type MailSystem_DeleteGlobalMailResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_DeleteGlobalMailResponse) Reset()         { *m = MailSystem_DeleteGlobalMailResponse{} }
func (m *MailSystem_DeleteGlobalMailResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_DeleteGlobalMailResponse) ProtoMessage()    {}
func (*MailSystem_DeleteGlobalMailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 20}
}

func (m *MailSystem_DeleteGlobalMailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailResponse.Unmarshal(m, b)
}
func (m *MailSystem_DeleteGlobalMailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_DeleteGlobalMailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_DeleteGlobalMailResponse.Merge(m, src)
}
func (m *MailSystem_DeleteGlobalMailResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_DeleteGlobalMailResponse.Size(m)
}
func (m *MailSystem_DeleteGlobalMailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_DeleteGlobalMailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_DeleteGlobalMailResponse proto.InternalMessageInfo

func (m *MailSystem_DeleteGlobalMailResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// 移除请求（删除已存在的邮件）
type MailSystem_RemoveRequest struct {
	// 玩家id
	PlayerId int64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	//移除策略,使用上面 Policy 枚举，为了使c++不奔溃.
	Policy int32 `protobuf:"varint,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// 需要移除的邮件id表, 除IN外，其他的只会使用数组的第0个元素,默认操作是IN
	Ids []int64 `protobuf:"varint,3,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// 是否为一键删除
	OneKeyRemove         bool     `protobuf:"varint,4,opt,name=oneKeyRemove,proto3" json:"oneKeyRemove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_RemoveRequest) Reset()         { *m = MailSystem_RemoveRequest{} }
func (m *MailSystem_RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_RemoveRequest) ProtoMessage()    {}
func (*MailSystem_RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 21}
}

func (m *MailSystem_RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_RemoveRequest.Unmarshal(m, b)
}
func (m *MailSystem_RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_RemoveRequest.Merge(m, src)
}
func (m *MailSystem_RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_RemoveRequest.Size(m)
}
func (m *MailSystem_RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_RemoveRequest proto.InternalMessageInfo

func (m *MailSystem_RemoveRequest) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MailSystem_RemoveRequest) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *MailSystem_RemoveRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *MailSystem_RemoveRequest) GetOneKeyRemove() bool {
	if m != nil {
		return m.OneKeyRemove
	}
	return false
}

// 移除响应
type MailSystem_RemoveResponse struct {
	// 本次成功移除的邮件id表
	SuccIds []int64 `protobuf:"varint,1,rep,packed,name=succIds,proto3" json:"succIds,omitempty"`
	// 本次删除失败的邮件id，以及对应的失败原因, value里的值使用的是FailCause的值
	FailIds              map[int64]int32 `protobuf:"bytes,4,rep,name=failIds,proto3" json:"failIds,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" bson:"-"`
}

func (m *MailSystem_RemoveResponse) Reset()         { *m = MailSystem_RemoveResponse{} }
func (m *MailSystem_RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_RemoveResponse) ProtoMessage()    {}
func (*MailSystem_RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 22}
}

func (m *MailSystem_RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_RemoveResponse.Unmarshal(m, b)
}
func (m *MailSystem_RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_RemoveResponse.Merge(m, src)
}
func (m *MailSystem_RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_RemoveResponse.Size(m)
}
func (m *MailSystem_RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_RemoveResponse proto.InternalMessageInfo

func (m *MailSystem_RemoveResponse) GetSuccIds() []int64 {
	if m != nil {
		return m.SuccIds
	}
	return nil
}

func (m *MailSystem_RemoveResponse) GetFailIds() map[int64]int32 {
	if m != nil {
		return m.FailIds
	}
	return nil
}

// 构建新的全局环境请求(如果只是取最新的全局环境，env放空就行）
type MailSystem_NewGlobalEnvRequest struct {
	// 提交给服务器的新环境
	Env                  map[string]*MailSystem_EnvWrap `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-" bson:"-"`
	XXX_unrecognized     []byte                         `json:"-" bson:"-"`
	XXX_sizecache        int32                          `json:"-" bson:"-"`
}

func (m *MailSystem_NewGlobalEnvRequest) Reset()         { *m = MailSystem_NewGlobalEnvRequest{} }
func (m *MailSystem_NewGlobalEnvRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_NewGlobalEnvRequest) ProtoMessage()    {}
func (*MailSystem_NewGlobalEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 23}
}

func (m *MailSystem_NewGlobalEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_NewGlobalEnvRequest.Unmarshal(m, b)
}
func (m *MailSystem_NewGlobalEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_NewGlobalEnvRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_NewGlobalEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_NewGlobalEnvRequest.Merge(m, src)
}
func (m *MailSystem_NewGlobalEnvRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_NewGlobalEnvRequest.Size(m)
}
func (m *MailSystem_NewGlobalEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_NewGlobalEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_NewGlobalEnvRequest proto.InternalMessageInfo

func (m *MailSystem_NewGlobalEnvRequest) GetEnv() map[string]*MailSystem_EnvWrap {
	if m != nil {
		return m.Env
	}
	return nil
}

//
type MailSystem_NewGlobalEnvResponse struct {
	// 拿到最新的所有环境,这个所有环境不是1秒后的，而是完全最新的，也就是说响应拿到的是最新的
	// 但系统本身是需要1秒后才能更新到本次提交的最新环境
	// 本次响应的所有环境是包括本次提交或修改的，以及以前存在的。
	Env map[string]*MailSystem_EnvValue `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 本次设置成功的env，给出来的都是环境的名称，这里指的是本次操作成功的
	SuccKeys             []string `protobuf:"bytes,2,rep,name=succKeys,proto3" json:"succKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_NewGlobalEnvResponse) Reset()         { *m = MailSystem_NewGlobalEnvResponse{} }
func (m *MailSystem_NewGlobalEnvResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_NewGlobalEnvResponse) ProtoMessage()    {}
func (*MailSystem_NewGlobalEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 24}
}

func (m *MailSystem_NewGlobalEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_NewGlobalEnvResponse.Unmarshal(m, b)
}
func (m *MailSystem_NewGlobalEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_NewGlobalEnvResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_NewGlobalEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_NewGlobalEnvResponse.Merge(m, src)
}
func (m *MailSystem_NewGlobalEnvResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_NewGlobalEnvResponse.Size(m)
}
func (m *MailSystem_NewGlobalEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_NewGlobalEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_NewGlobalEnvResponse proto.InternalMessageInfo

func (m *MailSystem_NewGlobalEnvResponse) GetEnv() map[string]*MailSystem_EnvValue {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *MailSystem_NewGlobalEnvResponse) GetSuccKeys() []string {
	if m != nil {
		return m.SuccKeys
	}
	return nil
}

// 移除全局环境请求
type MailSystem_RemoveGlobalEnvRequest struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *MailSystem_RemoveGlobalEnvRequest) Reset()         { *m = MailSystem_RemoveGlobalEnvRequest{} }
func (m *MailSystem_RemoveGlobalEnvRequest) String() string { return proto.CompactTextString(m) }
func (*MailSystem_RemoveGlobalEnvRequest) ProtoMessage()    {}
func (*MailSystem_RemoveGlobalEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 25}
}

func (m *MailSystem_RemoveGlobalEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest.Unmarshal(m, b)
}
func (m *MailSystem_RemoveGlobalEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest.Marshal(b, m, deterministic)
}
func (m *MailSystem_RemoveGlobalEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest.Merge(m, src)
}
func (m *MailSystem_RemoveGlobalEnvRequest) XXX_Size() int {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest.Size(m)
}
func (m *MailSystem_RemoveGlobalEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_RemoveGlobalEnvRequest proto.InternalMessageInfo

func (m *MailSystem_RemoveGlobalEnvRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type MailSystem_RemoveGlobalEnvResponse struct {
	// 状态码, 使用 StatusCode 的枚举值，为c++不奔溃
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 非 SUCCEED 下的错误信息
	ErrInfo string `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	// 拿到最新的所有环境,这个所有环境不是1秒后的，而是完全最新的,这里指的是所有还未被删除的
	// 但系统本身要在1秒后才能更新到删除的环境
	Env                  map[string]*MailSystem_EnvValue `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-" bson:"-"`
	XXX_unrecognized     []byte                          `json:"-" bson:"-"`
	XXX_sizecache        int32                           `json:"-" bson:"-"`
}

func (m *MailSystem_RemoveGlobalEnvResponse) Reset()         { *m = MailSystem_RemoveGlobalEnvResponse{} }
func (m *MailSystem_RemoveGlobalEnvResponse) String() string { return proto.CompactTextString(m) }
func (*MailSystem_RemoveGlobalEnvResponse) ProtoMessage()    {}
func (*MailSystem_RemoveGlobalEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 26}
}

func (m *MailSystem_RemoveGlobalEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse.Unmarshal(m, b)
}
func (m *MailSystem_RemoveGlobalEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse.Marshal(b, m, deterministic)
}
func (m *MailSystem_RemoveGlobalEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse.Merge(m, src)
}
func (m *MailSystem_RemoveGlobalEnvResponse) XXX_Size() int {
	return xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse.Size(m)
}
func (m *MailSystem_RemoveGlobalEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailSystem_RemoveGlobalEnvResponse proto.InternalMessageInfo

func (m *MailSystem_RemoveGlobalEnvResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MailSystem_RemoveGlobalEnvResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *MailSystem_RemoveGlobalEnvResponse) GetEnv() map[string]*MailSystem_EnvValue {
	if m != nil {
		return m.Env
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.MailSystem_SendResponse_StatusCode", MailSystem_SendResponse_StatusCode_name, MailSystem_SendResponse_StatusCode_value)
	proto.RegisterEnum("pb.MailSystem_ReadRequest_Operator", MailSystem_ReadRequest_Operator_name, MailSystem_ReadRequest_Operator_value)
	proto.RegisterEnum("pb.MailSystem_AttachResponse_StatusCode", MailSystem_AttachResponse_StatusCode_name, MailSystem_AttachResponse_StatusCode_value)
	proto.RegisterEnum("pb.MailSystem_SubmitResponse_StatusCode", MailSystem_SubmitResponse_StatusCode_name, MailSystem_SubmitResponse_StatusCode_value)
	proto.RegisterEnum("pb.MailSystem_RemoveRequest_Policy", MailSystem_RemoveRequest_Policy_name, MailSystem_RemoveRequest_Policy_value)
	proto.RegisterEnum("pb.MailSystem_RemoveResponse_FailCause", MailSystem_RemoveResponse_FailCause_name, MailSystem_RemoveResponse_FailCause_value)
	proto.RegisterEnum("pb.MailSystem_RemoveGlobalEnvResponse_StatusCode", MailSystem_RemoveGlobalEnvResponse_StatusCode_name, MailSystem_RemoveGlobalEnvResponse_StatusCode_value)
	proto.RegisterType((*MailSystem)(nil), "pb.MailSystem")
	proto.RegisterType((*MailSystem_EnvValue)(nil), "pb.MailSystem.EnvValue")
	proto.RegisterType((*MailSystem_EnvWrap)(nil), "pb.MailSystem.EnvWrap")
	proto.RegisterType((*MailSystem_PlayerInfo)(nil), "pb.MailSystem.PlayerInfo")
	proto.RegisterType((*MailSystem_SystemInfo)(nil), "pb.MailSystem.SystemInfo")
	proto.RegisterType((*MailSystem_Box)(nil), "pb.MailSystem.Box")
	proto.RegisterMapType((map[int64]*MailSystem_GlobalMail)(nil), "pb.MailSystem.Box.GMailsEntry")
	proto.RegisterMapType((map[int64]*MailSystem_Mail)(nil), "pb.MailSystem.Box.MailsEntry")
	proto.RegisterType((*MailSystem_Mail)(nil), "pb.MailSystem.Mail")
	proto.RegisterType((*MailSystem_GlobalMail)(nil), "pb.MailSystem.GlobalMail")
	proto.RegisterType((*MailSystem_Attachment)(nil), "pb.MailSystem.Attachment")
	proto.RegisterType((*MailSystem_SendRequest)(nil), "pb.MailSystem.SendRequest")
	proto.RegisterType((*MailSystem_SendResponse)(nil), "pb.MailSystem.SendResponse")
	proto.RegisterType((*MailSystem_PullRequest)(nil), "pb.MailSystem.PullRequest")
	proto.RegisterMapType((map[string]*MailSystem_EnvValue)(nil), "pb.MailSystem.PullRequest.EnvEntry")
	proto.RegisterType((*MailSystem_PullResponse)(nil), "pb.MailSystem.PullResponse")
	proto.RegisterType((*MailSystem_ReadRequest)(nil), "pb.MailSystem.ReadRequest")
	proto.RegisterType((*MailSystem_ReadResponse)(nil), "pb.MailSystem.ReadResponse")
	proto.RegisterType((*MailSystem_AttachRequest)(nil), "pb.MailSystem.AttachRequest")
	proto.RegisterType((*MailSystem_AttachResponse)(nil), "pb.MailSystem.AttachResponse")
	proto.RegisterMapType((map[int64]*MailSystem_AttachmentPack)(nil), "pb.MailSystem.AttachResponse.PacksEntry")
	proto.RegisterType((*MailSystem_AttachmentPack)(nil), "pb.MailSystem.AttachmentPack")
	proto.RegisterType((*MailSystem_SubmitRequest)(nil), "pb.MailSystem.SubmitRequest")
	proto.RegisterMapType((map[string]*MailSystem_EnvValue)(nil), "pb.MailSystem.SubmitRequest.TestParamEntry")
	proto.RegisterType((*MailSystem_SubmitResponse)(nil), "pb.MailSystem.SubmitResponse")
	proto.RegisterType((*MailSystem_DeleteGlobalMailRequest)(nil), "pb.MailSystem.DeleteGlobalMailRequest")
	proto.RegisterType((*MailSystem_DeleteGlobalMailResponse)(nil), "pb.MailSystem.DeleteGlobalMailResponse")
	proto.RegisterType((*MailSystem_RemoveRequest)(nil), "pb.MailSystem.RemoveRequest")
	proto.RegisterType((*MailSystem_RemoveResponse)(nil), "pb.MailSystem.RemoveResponse")
	proto.RegisterMapType((map[int64]int32)(nil), "pb.MailSystem.RemoveResponse.FailIdsEntry")
	proto.RegisterType((*MailSystem_NewGlobalEnvRequest)(nil), "pb.MailSystem.NewGlobalEnvRequest")
	proto.RegisterMapType((map[string]*MailSystem_EnvWrap)(nil), "pb.MailSystem.NewGlobalEnvRequest.EnvEntry")
	proto.RegisterType((*MailSystem_NewGlobalEnvResponse)(nil), "pb.MailSystem.NewGlobalEnvResponse")
	proto.RegisterMapType((map[string]*MailSystem_EnvValue)(nil), "pb.MailSystem.NewGlobalEnvResponse.EnvEntry")
	proto.RegisterType((*MailSystem_RemoveGlobalEnvRequest)(nil), "pb.MailSystem.RemoveGlobalEnvRequest")
	proto.RegisterType((*MailSystem_RemoveGlobalEnvResponse)(nil), "pb.MailSystem.RemoveGlobalEnvResponse")
	proto.RegisterMapType((map[string]*MailSystem_EnvValue)(nil), "pb.MailSystem.RemoveGlobalEnvResponse.EnvEntry")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 1779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0xd7, 0x90, 0x92, 0x2c, 0x3d, 0x39, 0x0e, 0x31, 0x09, 0x12, 0x96, 0x9b, 0x3f, 0x06, 0xb3,
	0x4d, 0xbc, 0xdd, 0xac, 0x8d, 0x38, 0xdb, 0xdd, 0xc5, 0x76, 0x37, 0x80, 0x6c, 0xd3, 0x8e, 0x10,
	0xc7, 0x72, 0x47, 0xcc, 0x66, 0x7b, 0x12, 0x68, 0x71, 0x9c, 0x12, 0x91, 0x48, 0x95, 0xa4, 0x54,
	0xeb, 0xde, 0x6b, 0x3f, 0x44, 0x81, 0x7e, 0x8f, 0x1e, 0xda, 0x0f, 0xd0, 0x5b, 0x8f, 0x29, 0xd2,
	0x5b, 0xfb, 0x15, 0x0a, 0x6c, 0x31, 0x33, 0xa4, 0x38, 0x24, 0x25, 0xff, 0x49, 0x93, 0x8b, 0x39,
	0x6f, 0xde, 0x7b, 0xf3, 0xfe, 0xfe, 0xde, 0x53, 0x00, 0x46, 0x8e, 0x37, 0xdc, 0x1c, 0x87, 0x41,
	0x1c, 0x60, 0x65, 0x7c, 0x62, 0x7c, 0x3a, 0x08, 0x46, 0xa3, 0xc0, 0x8f, 0xbe, 0x78, 0x13, 0x6c,
	0x4d, 0x9d, 0xa1, 0xe7, 0x3a, 0x71, 0x10, 0x66, 0x5f, 0x82, 0xd3, 0xfc, 0xd7, 0x03, 0x80, 0x97,
	0x8e, 0x37, 0xec, 0xcd, 0xa2, 0x98, 0x8e, 0x8c, 0x27, 0xd0, 0xb0, 0xfc, 0xe9, 0x0f, 0xce, 0x70,
	0x42, 0xf1, 0x1a, 0xa0, 0x48, 0x47, 0xeb, 0x68, 0xa3, 0xf9, 0xbc, 0x42, 0x50, 0xc4, 0xce, 0xa7,
	0xba, 0xb2, 0x8e, 0x36, 0x10, 0x3b, 0x9f, 0xee, 0xd4, 0x40, 0x9d, 0x3a, 0x43, 0xc3, 0x83, 0x15,
	0xcb, 0x9f, 0xbe, 0x0e, 0x9d, 0x31, 0x7e, 0xc2, 0x29, 0x5c, 0xa6, 0xb5, 0x7d, 0x7b, 0x73, 0x7c,
	0xb2, 0x99, 0xa9, 0xde, 0x4c, 0xf5, 0xee, 0xd4, 0xdf, 0xbf, 0xbb, 0xaf, 0x7c, 0x83, 0x08, 0xe3,
	0xc5, 0x9f, 0x43, 0xc3, 0x9d, 0x84, 0x4e, 0xec, 0x05, 0x3e, 0xd7, 0xad, 0xee, 0x5c, 0x7f, 0xff,
	0xee, 0x7e, 0x4b, 0xfb, 0x29, 0xfd, 0x87, 0xc8, 0x9c, 0xc1, 0xb0, 0x01, 0x8e, 0x87, 0xce, 0x8c,
	0x86, 0x1d, 0xff, 0x34, 0xc0, 0xb7, 0x40, 0xf1, 0x5c, 0xfe, 0x98, 0x2a, 0x74, 0x6a, 0x15, 0xa2,
	0x78, 0x2e, 0x36, 0xa0, 0xea, 0x3b, 0x23, 0xca, 0xd5, 0x35, 0xc5, 0xcd, 0x18, 0x11, 0x4e, 0xc3,
	0x18, 0xaa, 0xae, 0x13, 0x3b, 0xba, 0xba, 0x8e, 0x36, 0x56, 0x09, 0xff, 0x36, 0xbe, 0x03, 0x10,
	0x26, 0x72, 0xad, 0xa9, 0x34, 0x3a, 0x47, 0x5a, 0x91, 0xa4, 0x7f, 0x52, 0x40, 0xdd, 0x09, 0xce,
	0xb0, 0x01, 0x8d, 0xb1, 0xb0, 0x2d, 0xb1, 0x89, 0xcc, 0xcf, 0x58, 0x87, 0x95, 0x37, 0xdd, 0xd3,
	0xd3, 0x88, 0xc6, 0xc2, 0x47, 0x92, 0x1e, 0xf1, 0x2d, 0xa8, 0xfb, 0xf4, 0x2c, 0xee, 0xb8, 0xdc,
	0x22, 0x95, 0x24, 0x27, 0x26, 0x31, 0xa5, 0x61, 0xc4, 0xa2, 0x52, 0x15, 0x12, 0xc9, 0x11, 0x3f,
	0x85, 0x1a, 0x4b, 0x74, 0xa4, 0xd7, 0xd6, 0xd5, 0x8d, 0xd6, 0xf6, 0xdd, 0x42, 0x94, 0x77, 0x82,
	0x33, 0x7e, 0x8c, 0x2c, 0x3f, 0x0e, 0x67, 0x44, 0xf0, 0xe2, 0xaf, 0xa0, 0xfe, 0x86, 0x53, 0xf5,
	0x3a, 0x97, 0xba, 0xb7, 0x40, 0xea, 0x40, 0x12, 0x4b, 0xb8, 0x8d, 0x97, 0xa2, 0x38, 0x04, 0x15,
	0x6b, 0xa0, 0xbe, 0xa5, 0xb3, 0xc4, 0x3b, 0xf6, 0x89, 0x3f, 0x83, 0xda, 0x94, 0xe5, 0x94, 0xbb,
	0xd5, 0xda, 0xbe, 0x51, 0x50, 0xcb, 0x3e, 0x89, 0xe0, 0xf8, 0x56, 0xf9, 0x06, 0x19, 0x36, 0xb4,
	0x0e, 0xce, 0xd5, 0xb7, 0x95, 0xd7, 0xf7, 0xb3, 0x82, 0xbe, 0x83, 0x61, 0x70, 0xe2, 0x0c, 0x8b,
	0x5a, 0xff, 0xab, 0x40, 0x95, 0xd1, 0xf0, 0x5a, 0x56, 0x10, 0xbc, 0x10, 0x1e, 0x02, 0x84, 0x74,
	0x40, 0xbd, 0x29, 0x4f, 0x8a, 0x92, 0x2b, 0x14, 0xe9, 0x06, 0x3f, 0x81, 0x7a, 0x44, 0x7d, 0x97,
	0x86, 0x3c, 0x09, 0xe5, 0x67, 0xb3, 0x9a, 0x23, 0x09, 0x23, 0xbe, 0x03, 0xb5, 0xd8, 0x8b, 0x87,
	0x94, 0x67, 0x27, 0x2b, 0x13, 0x41, 0x64, 0xd9, 0x1b, 0x04, 0x7e, 0x4c, 0xfd, 0x58, 0xaf, 0xb1,
	0x7b, 0x92, 0x1e, 0x59, 0x05, 0x85, 0xd4, 0x71, 0xf5, 0xfa, 0x3a, 0xda, 0x68, 0x10, 0xfe, 0x8d,
	0x3f, 0x85, 0x6b, 0xce, 0x70, 0xd8, 0x8e, 0x63, 0x67, 0xf0, 0xdb, 0xbd, 0xc0, 0xa7, 0xfa, 0x0a,
	0xbf, 0xcc, 0x13, 0x59, 0x7d, 0xb1, 0xb7, 0x6d, 0x6f, 0x44, 0xf5, 0x86, 0xa8, 0xaf, 0xf4, 0x8c,
	0xef, 0x01, 0xd0, 0xb3, 0xb1, 0x17, 0x52, 0x7e, 0xdb, 0xe4, 0xb7, 0x12, 0x05, 0xff, 0x0a, 0x5a,
	0x0e, 0xd7, 0xd4, 0x0e, 0x43, 0x67, 0xa6, 0x03, 0xaf, 0x81, 0xa2, 0x97, 0xe2, 0xad, 0x11, 0xf5,
	0x63, 0x22, 0x73, 0x0b, 0xe5, 0x31, 0xf5, 0xdd, 0x3d, 0x56, 0xfa, 0x2d, 0x5e, 0xfa, 0x12, 0xc5,
	0xf8, 0xa7, 0x02, 0x90, 0x25, 0xa6, 0x94, 0x84, 0x7b, 0x00, 0xd1, 0x20, 0xf4, 0xc6, 0xb1, 0x3d,
	0x1b, 0x27, 0x3d, 0x49, 0x24, 0x0a, 0xbb, 0x1f, 0x04, 0xbe, 0xdb, 0xe3, 0x14, 0x9e, 0x80, 0x26,
	0x91, 0x28, 0x52, 0x72, 0xaa, 0x0b, 0x93, 0x93, 0xb5, 0x6e, 0x39, 0x39, 0xb5, 0x0b, 0x92, 0x53,
	0xcf, 0x27, 0x47, 0x0e, 0xf1, 0xca, 0xb9, 0x21, 0x6e, 0x5c, 0x14, 0xe2, 0xe6, 0xff, 0x11, 0x62,
	0x28, 0x85, 0xf8, 0x4b, 0x80, 0x4c, 0x94, 0xd5, 0xd0, 0xc8, 0x09, 0xdf, 0xf2, 0x18, 0x37, 0x08,
	0xff, 0x5e, 0x88, 0x4c, 0xcf, 0xa0, 0xd5, 0xa3, 0xbe, 0x4b, 0xe8, 0xef, 0x26, 0x34, 0x8a, 0xf1,
	0x16, 0x13, 0xf3, 0x52, 0x74, 0x5e, 0xd4, 0xaa, 0x73, 0x64, 0xe6, 0x8c, 0xc6, 0x5f, 0x10, 0xac,
	0x0a, 0x05, 0xd1, 0x38, 0xf0, 0x23, 0xca, 0xc0, 0x2a, 0x8a, 0x9d, 0x78, 0x22, 0xa6, 0x42, 0x8d,
	0x24, 0x27, 0x16, 0x51, 0x1a, 0xf2, 0xfe, 0x48, 0xf2, 0x9b, 0x1e, 0xf1, 0xa3, 0xe4, 0x4d, 0x75,
	0x39, 0x3c, 0x70, 0x06, 0xd6, 0x03, 0x21, 0x1d, 0x05, 0x53, 0xca, 0x68, 0x1d, 0x37, 0xd2, 0xab,
	0xeb, 0xea, 0x86, 0x4a, 0xf2, 0x44, 0x73, 0x13, 0xa0, 0xc7, 0x9f, 0xdc, 0x0d, 0x5c, 0x8a, 0x5b,
	0xb0, 0xd2, 0x7b, 0xb5, 0xbb, 0x6b, 0x59, 0x7b, 0x5a, 0x05, 0xdf, 0x80, 0xeb, 0xdd, 0x1f, 0x2c,
	0xb2, 0x7f, 0xd8, 0x7d, 0xdd, 0x27, 0xd6, 0xfe, 0xab, 0x9e, 0xa5, 0x21, 0xe3, 0xdf, 0x08, 0x5a,
	0xc7, 0x93, 0xe1, 0x30, 0x0d, 0x81, 0x59, 0xc4, 0xe8, 0x39, 0x1c, 0x64, 0x58, 0xbd, 0x25, 0x06,
	0xa9, 0x0c, 0xd7, 0xe5, 0x91, 0x24, 0xb1, 0xe0, 0x5f, 0x82, 0x4a, 0xfd, 0xa9, 0xae, 0xf2, 0x8c,
	0x3f, 0x28, 0x42, 0x47, 0xf6, 0x3a, 0x1b, 0x80, 0x02, 0x5d, 0x19, 0xbf, 0xd1, 0xe5, 0x93, 0xb6,
	0x04, 0x84, 0x4d, 0x01, 0x84, 0x5f, 0xe4, 0x81, 0x70, 0xd9, 0x2c, 0x95, 0x61, 0xb0, 0x0f, 0xab,
	0xe2, 0xb5, 0x24, 0x5b, 0x9f, 0xa5, 0x83, 0x42, 0x58, 0xb6, 0x18, 0x9b, 0xc5, 0x78, 0xb8, 0x54,
	0xf4, 0x8d, 0x77, 0x08, 0x5a, 0x84, 0x3a, 0xee, 0x55, 0xa2, 0xa9, 0x83, 0xea, 0xb9, 0x91, 0xae,
	0x30, 0x7d, 0xe2, 0xfa, 0x0c, 0x11, 0x46, 0xc2, 0x3a, 0x28, 0xc1, 0x98, 0x17, 0x46, 0x6d, 0xa7,
	0xf1, 0xfe, 0xdd, 0xfd, 0xaa, 0x5e, 0xd9, 0xa8, 0x11, 0x25, 0x18, 0xe3, 0x3b, 0xd0, 0xf4, 0x29,
	0x75, 0xc5, 0xbc, 0xaa, 0xf2, 0x22, 0xcf, 0x08, 0xec, 0xd6, 0x61, 0x5e, 0xc6, 0x93, 0xd0, 0xe7,
	0x0d, 0xde, 0x20, 0x19, 0xc1, 0xfc, 0x0e, 0x1a, 0xdd, 0x31, 0x0d, 0xd9, 0x82, 0x83, 0xeb, 0xa0,
	0x74, 0x8e, 0xb4, 0x0a, 0xfb, 0x6b, 0xfd, 0x5a, 0x43, 0xec, 0xef, 0x81, 0xad, 0x29, 0x78, 0x05,
	0xd4, 0x03, 0xdb, 0xd2, 0x54, 0x46, 0x38, 0xb4, 0xb5, 0x2a, 0x23, 0x1c, 0xda, 0x96, 0x56, 0x33,
	0x5e, 0xc0, 0xaa, 0x70, 0x30, 0x09, 0xa1, 0x26, 0xac, 0x47, 0x3c, 0x1a, 0xdc, 0xea, 0x79, 0x50,
	0x95, 0x8b, 0x82, 0x6a, 0xfc, 0x01, 0xc1, 0x35, 0xd1, 0xb5, 0x57, 0x09, 0xd8, 0x23, 0xa8, 0x8f,
	0x78, 0xbc, 0x97, 0x95, 0x5e, 0x72, 0x8d, 0x1f, 0xc2, 0x9a, 0x80, 0x90, 0x8e, 0x7b, 0x26, 0x30,
	0x87, 0xe5, 0xb9, 0x46, 0x0a, 0x54, 0xe3, 0x1f, 0x0a, 0xac, 0xa5, 0x66, 0x7c, 0x70, 0x1f, 0x3f,
	0x83, 0xda, 0xd8, 0x19, 0xbc, 0x4d, 0x6b, 0x69, 0x63, 0x21, 0xae, 0xa5, 0xfa, 0x37, 0x8f, 0x19,
	0x6b, 0xb2, 0x7f, 0x70, 0xb1, 0x4b, 0x16, 0xd8, 0x6b, 0x80, 0x4c, 0x74, 0xc1, 0x76, 0xf0, 0x34,
	0xdf, 0x14, 0x77, 0x97, 0xa2, 0x2b, 0xd3, 0x22, 0xb5, 0x86, 0x69, 0x2f, 0xc7, 0x0d, 0x0c, 0x6b,
	0x2f, 0xdb, 0x9d, 0xc3, 0xfe, 0x51, 0xd7, 0xee, 0x5b, 0x3f, 0x76, 0x7a, 0xb6, 0x86, 0xf0, 0x4d,
	0xd0, 0xda, 0xb6, 0xdd, 0xde, 0x7d, 0x2e, 0x51, 0x15, 0x7c, 0x1d, 0x5a, 0x9c, 0xd3, 0xfa, 0xf1,
	0xb8, 0x43, 0x2c, 0x4d, 0x35, 0x5e, 0xa6, 0x81, 0x4d, 0x9f, 0x2c, 0x0e, 0x01, 0x74, 0x95, 0x21,
	0xc0, 0xc0, 0xea, 0x5a, 0x6f, 0x72, 0x32, 0xf2, 0xe2, 0xb4, 0x5e, 0xbe, 0x86, 0xda, 0x1b, 0x09,
	0xb2, 0x97, 0x6f, 0x43, 0x73, 0xe0, 0x16, 0xfc, 0xb8, 0x03, 0xcd, 0x98, 0x46, 0xf1, 0xb1, 0x13,
	0x3a, 0xa3, 0xa4, 0x52, 0x3f, 0x2f, 0x8e, 0x4d, 0xf9, 0xa5, 0x4d, 0x3b, 0xe5, 0x16, 0x59, 0xcb,
	0xa4, 0x8d, 0x57, 0xb0, 0x96, 0xbf, 0xfc, 0x38, 0x60, 0xf5, 0x47, 0x04, 0x6b, 0xa9, 0x09, 0x1f,
	0x5c, 0x95, 0x6c, 0xad, 0x66, 0xfe, 0x7a, 0xe9, 0xf6, 0x9c, 0x1e, 0xcd, 0xad, 0xe5, 0x09, 0xbf,
	0x09, 0x5a, 0x6f, 0x97, 0x74, 0x8e, 0xed, 0xbe, 0x6d, 0xf5, 0xec, 0xfe, 0x7e, 0xa7, 0x7d, 0xa8,
	0x21, 0xe3, 0x29, 0xdc, 0xde, 0xa3, 0x43, 0x1a, 0x53, 0x69, 0xc5, 0x4c, 0xb2, 0xa0, 0x4b, 0x20,
	0x90, 0x83, 0x30, 0xe3, 0x31, 0xe8, 0x65, 0xa1, 0x65, 0xd0, 0x61, 0xfc, 0x0d, 0xc1, 0x35, 0xc2,
	0xeb, 0xfd, 0x2a, 0x78, 0xb0, 0x0e, 0xf5, 0x71, 0x30, 0xf4, 0x06, 0x33, 0xee, 0x7c, 0x06, 0x95,
	0x2a, 0x49, 0xe8, 0xe9, 0x4b, 0x6a, 0x06, 0x52, 0x26, 0xac, 0x06, 0x3e, 0x7d, 0x41, 0x67, 0xe2,
	0xb9, 0x04, 0x43, 0x73, 0x34, 0xf3, 0x6b, 0xa8, 0x1f, 0x0b, 0xf9, 0x3a, 0x28, 0x47, 0x5d, 0xad,
	0x82, 0x01, 0xea, 0xa2, 0xea, 0x35, 0x84, 0x1b, 0x50, 0x25, 0x56, 0x7b, 0x4f, 0x54, 0x3d, 0xfb,
	0xea, 0x27, 0x57, 0xaa, 0xf1, 0x1f, 0x04, 0x6b, 0xa9, 0x1b, 0x89, 0xaf, 0x3a, 0xac, 0x44, 0x93,
	0xc1, 0xa0, 0x33, 0xf7, 0x37, 0x3d, 0xe2, 0x3d, 0x58, 0x39, 0x95, 0x3a, 0xbe, 0xb5, 0xfd, 0x8b,
	0x42, 0x6d, 0xe4, 0x35, 0x6d, 0xee, 0x0b, 0x66, 0x51, 0x85, 0xa9, 0xa8, 0xf1, 0x2d, 0xac, 0xca,
	0x17, 0x0b, 0x90, 0xe1, 0xa6, 0x5c, 0x81, 0x35, 0xb9, 0xf5, 0xbf, 0x87, 0x26, 0x93, 0xdd, 0x75,
	0x26, 0x3c, 0x29, 0xab, 0xbc, 0x9b, 0x53, 0x6f, 0xb8, 0xd3, 0xaf, 0x8e, 0xb8, 0xab, 0x68, 0x01,
	0x14, 0x28, 0xc6, 0x9f, 0x11, 0xdc, 0x38, 0xa2, 0xbf, 0x17, 0x09, 0xb6, 0xfc, 0x69, 0x9a, 0xba,
	0xef, 0xc5, 0xd0, 0x47, 0x0b, 0x7b, 0x6b, 0x81, 0x40, 0x61, 0xf8, 0x1f, 0x9d, 0x3b, 0xfc, 0x1f,
	0xe7, 0xfb, 0xe9, 0x56, 0xb9, 0x9f, 0xd8, 0xaf, 0x6d, 0xb9, 0x9d, 0xfe, 0x8a, 0xe0, 0x66, 0xfe,
	0xd5, 0x24, 0x35, 0xcf, 0x64, 0x3b, 0x1f, 0x9f, 0x6b, 0x67, 0x92, 0x82, 0x9c, 0xa1, 0x7c, 0x25,
	0x9e, 0x0c, 0x06, 0x2f, 0xe8, 0x4c, 0x8c, 0xbc, 0x26, 0x99, 0x9f, 0x3f, 0xfe, 0x06, 0xf3, 0x25,
	0xdc, 0x12, 0xf5, 0x50, 0x0a, 0xb7, 0x01, 0xd5, 0xb7, 0xcc, 0x04, 0xe6, 0x47, 0x73, 0xde, 0x84,
	0x9c, 0x66, 0xfc, 0x49, 0x81, 0xdb, 0x25, 0xb1, 0xc4, 0xfd, 0xf5, 0x3c, 0xa6, 0xcc, 0xbb, 0x07,
	0x5d, 0x02, 0x5d, 0xda, 0xf2, 0x5e, 0xb7, 0xb5, 0xb0, 0x6e, 0x2f, 0x88, 0xde, 0x47, 0x8f, 0x90,
	0xf9, 0xd5, 0x72, 0x5c, 0xfb, 0x04, 0x6e, 0x1f, 0x76, 0xdb, 0x7b, 0xfd, 0x7d, 0x56, 0xc2, 0xaf,
	0x3b, 0xf6, 0xf3, 0xfe, 0x9e, 0x75, 0xd8, 0x67, 0xf7, 0x1a, 0xda, 0xfe, 0x7b, 0x2d, 0xf9, 0x89,
	0xdc, 0x86, 0x2a, 0x5b, 0xe9, 0xb1, 0x51, 0x1c, 0x07, 0xd9, 0x0f, 0x05, 0xe3, 0x93, 0x85, 0x77,
	0xc2, 0x41, 0xb3, 0xc2, 0x54, 0xb0, 0x3d, 0xb3, 0xa4, 0x42, 0x5a, 0x75, 0x4b, 0x2a, 0xe4, 0xc5,
	0x54, 0xa8, 0x60, 0x7b, 0x56, 0x49, 0x85, 0xb4, 0x5d, 0x96, 0x54, 0xc8, 0x8b, 0x99, 0x59, 0xc1,
	0x07, 0x50, 0x17, 0x83, 0x14, 0xdf, 0x59, 0xb2, 0x8c, 0x08, 0x35, 0x77, 0xcf, 0x5d, 0x55, 0x84,
	0x22, 0x31, 0x88, 0x4a, 0x8a, 0x72, 0x23, 0xb2, 0xa4, 0x28, 0x3f, 0xbd, 0xcc, 0x0a, 0xa6, 0xa0,
	0x15, 0xa7, 0x01, 0x7e, 0x58, 0x10, 0x5a, 0x32, 0x63, 0x8c, 0x47, 0x17, 0xf2, 0xc9, 0xf6, 0x8a,
	0xe2, 0x2b, 0xd9, 0x9b, 0x1b, 0x2e, 0x25, 0x7b, 0xf3, 0x48, 0x6b, 0x56, 0xf0, 0x6f, 0x60, 0x55,
	0x06, 0x00, 0x6c, 0x5e, 0x8c, 0x62, 0xc6, 0x83, 0x4b, 0x20, 0x88, 0x59, 0xc1, 0x27, 0x70, 0xbd,
	0xd0, 0x20, 0xf8, 0xe7, 0x17, 0x35, 0x90, 0x78, 0xe0, 0xe1, 0xe5, 0xfa, 0xcc, 0xac, 0x9c, 0xd4,
	0xf9, 0xff, 0x5f, 0x3e, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xe4, 0xb0, 0xca, 0xf7,
	0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailClient is the client API for Mail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailClient interface {
	// 发送邮件
	Send(ctx context.Context, in *MailSystem_SendRequest, opts ...grpc.CallOption) (*MailSystem_SendResponse, error)
	// 拉取邮件，同时也是心跳拉取
	Pull(ctx context.Context, in *MailSystem_PullRequest, opts ...grpc.CallOption) (*MailSystem_PullResponse, error)
	// 读取邮件(标记邮件是否已读取)
	Read(ctx context.Context, in *MailSystem_ReadRequest, opts ...grpc.CallOption) (*MailSystem_ReadResponse, error)
	// 领取附件
	Attach(ctx context.Context, in *MailSystem_AttachRequest, opts ...grpc.CallOption) (*MailSystem_AttachResponse, error)
	// 提交邮件（提交是指由运营或游戏中发放的全服邮件)
	Submit(ctx context.Context, in *MailSystem_SubmitRequest, opts ...grpc.CallOption) (*MailSystem_SubmitResponse, error)
	// 删除全局邮件
	DeleteGlobalMail(ctx context.Context, in *MailSystem_DeleteGlobalMailRequest, opts ...grpc.CallOption) (*MailSystem_DeleteGlobalMailResponse, error)
	// 移除邮件
	Remove(ctx context.Context, in *MailSystem_RemoveRequest, opts ...grpc.CallOption) (*MailSystem_RemoveResponse, error)
	// 构建新环境，在同样名称的环境下，优先使用局部环境
	// 新构建的环境，至少要在1秒钟之后才会生效
	NewGlobalEnv(ctx context.Context, in *MailSystem_NewGlobalEnvRequest, opts ...grpc.CallOption) (*MailSystem_NewGlobalEnvResponse, error)
	// 删除环境，删除的环境要在1秒钟之后才会生效
	RemoveGlobalEnv(ctx context.Context, in *MailSystem_RemoveGlobalEnvRequest, opts ...grpc.CallOption) (*MailSystem_RemoveGlobalEnvResponse, error)
}

type mailClient struct {
	cc *grpc.ClientConn
}

func NewMailClient(cc *grpc.ClientConn) MailClient {
	return &mailClient{cc}
}

func (c *mailClient) Send(ctx context.Context, in *MailSystem_SendRequest, opts ...grpc.CallOption) (*MailSystem_SendResponse, error) {
	out := new(MailSystem_SendResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) Pull(ctx context.Context, in *MailSystem_PullRequest, opts ...grpc.CallOption) (*MailSystem_PullResponse, error) {
	out := new(MailSystem_PullResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) Read(ctx context.Context, in *MailSystem_ReadRequest, opts ...grpc.CallOption) (*MailSystem_ReadResponse, error) {
	out := new(MailSystem_ReadResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) Attach(ctx context.Context, in *MailSystem_AttachRequest, opts ...grpc.CallOption) (*MailSystem_AttachResponse, error) {
	out := new(MailSystem_AttachResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Attach", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) Submit(ctx context.Context, in *MailSystem_SubmitRequest, opts ...grpc.CallOption) (*MailSystem_SubmitResponse, error) {
	out := new(MailSystem_SubmitResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) DeleteGlobalMail(ctx context.Context, in *MailSystem_DeleteGlobalMailRequest, opts ...grpc.CallOption) (*MailSystem_DeleteGlobalMailResponse, error) {
	out := new(MailSystem_DeleteGlobalMailResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/DeleteGlobalMail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) Remove(ctx context.Context, in *MailSystem_RemoveRequest, opts ...grpc.CallOption) (*MailSystem_RemoveResponse, error) {
	out := new(MailSystem_RemoveResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) NewGlobalEnv(ctx context.Context, in *MailSystem_NewGlobalEnvRequest, opts ...grpc.CallOption) (*MailSystem_NewGlobalEnvResponse, error) {
	out := new(MailSystem_NewGlobalEnvResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/NewGlobalEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailClient) RemoveGlobalEnv(ctx context.Context, in *MailSystem_RemoveGlobalEnvRequest, opts ...grpc.CallOption) (*MailSystem_RemoveGlobalEnvResponse, error) {
	out := new(MailSystem_RemoveGlobalEnvResponse)
	err := c.cc.Invoke(ctx, "/pb.Mail/RemoveGlobalEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServer is the server API for Mail service.
type MailServer interface {
	// 发送邮件
	Send(context.Context, *MailSystem_SendRequest) (*MailSystem_SendResponse, error)
	// 拉取邮件，同时也是心跳拉取
	Pull(context.Context, *MailSystem_PullRequest) (*MailSystem_PullResponse, error)
	// 读取邮件(标记邮件是否已读取)
	Read(context.Context, *MailSystem_ReadRequest) (*MailSystem_ReadResponse, error)
	// 领取附件
	Attach(context.Context, *MailSystem_AttachRequest) (*MailSystem_AttachResponse, error)
	// 提交邮件（提交是指由运营或游戏中发放的全服邮件)
	Submit(context.Context, *MailSystem_SubmitRequest) (*MailSystem_SubmitResponse, error)
	// 删除全局邮件
	DeleteGlobalMail(context.Context, *MailSystem_DeleteGlobalMailRequest) (*MailSystem_DeleteGlobalMailResponse, error)
	// 移除邮件
	Remove(context.Context, *MailSystem_RemoveRequest) (*MailSystem_RemoveResponse, error)
	// 构建新环境，在同样名称的环境下，优先使用局部环境
	// 新构建的环境，至少要在1秒钟之后才会生效
	NewGlobalEnv(context.Context, *MailSystem_NewGlobalEnvRequest) (*MailSystem_NewGlobalEnvResponse, error)
	// 删除环境，删除的环境要在1秒钟之后才会生效
	RemoveGlobalEnv(context.Context, *MailSystem_RemoveGlobalEnvRequest) (*MailSystem_RemoveGlobalEnvResponse, error)
}

// UnimplementedMailServer can be embedded to have forward compatible implementations.
type UnimplementedMailServer struct {
}

func (*UnimplementedMailServer) Send(ctx context.Context, req *MailSystem_SendRequest) (*MailSystem_SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedMailServer) Pull(ctx context.Context, req *MailSystem_PullRequest) (*MailSystem_PullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedMailServer) Read(ctx context.Context, req *MailSystem_ReadRequest) (*MailSystem_ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedMailServer) Attach(ctx context.Context, req *MailSystem_AttachRequest) (*MailSystem_AttachResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (*UnimplementedMailServer) Submit(ctx context.Context, req *MailSystem_SubmitRequest) (*MailSystem_SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedMailServer) DeleteGlobalMail(ctx context.Context, req *MailSystem_DeleteGlobalMailRequest) (*MailSystem_DeleteGlobalMailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGlobalMail not implemented")
}
func (*UnimplementedMailServer) Remove(ctx context.Context, req *MailSystem_RemoveRequest) (*MailSystem_RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedMailServer) NewGlobalEnv(ctx context.Context, req *MailSystem_NewGlobalEnvRequest) (*MailSystem_NewGlobalEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGlobalEnv not implemented")
}
func (*UnimplementedMailServer) RemoveGlobalEnv(ctx context.Context, req *MailSystem_RemoveGlobalEnvRequest) (*MailSystem_RemoveGlobalEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveGlobalEnv not implemented")
}

func RegisterMailServer(s *grpc.Server, srv MailServer) {
	s.RegisterService(&_Mail_serviceDesc, srv)
}

func _Mail_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Send(ctx, req.(*MailSystem_SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Pull(ctx, req.(*MailSystem_PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Read(ctx, req.(*MailSystem_ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Attach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Attach(ctx, req.(*MailSystem_AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Submit(ctx, req.(*MailSystem_SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_DeleteGlobalMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_DeleteGlobalMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).DeleteGlobalMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/DeleteGlobalMail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).DeleteGlobalMail(ctx, req.(*MailSystem_DeleteGlobalMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Remove(ctx, req.(*MailSystem_RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_NewGlobalEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_NewGlobalEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).NewGlobalEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/NewGlobalEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).NewGlobalEnv(ctx, req.(*MailSystem_NewGlobalEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mail_RemoveGlobalEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSystem_RemoveGlobalEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).RemoveGlobalEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Mail/RemoveGlobalEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).RemoveGlobalEnv(ctx, req.(*MailSystem_RemoveGlobalEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Mail",
	HandlerType: (*MailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Mail_Send_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Mail_Pull_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Mail_Read_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _Mail_Attach_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Mail_Submit_Handler,
		},
		{
			MethodName: "DeleteGlobalMail",
			Handler:    _Mail_DeleteGlobalMail_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Mail_Remove_Handler,
		},
		{
			MethodName: "NewGlobalEnv",
			Handler:    _Mail_NewGlobalEnv_Handler,
		},
		{
			MethodName: "RemoveGlobalEnv",
			Handler:    _Mail_RemoveGlobalEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
